### ISSUE TITLE
Import from statements not supported

### ISSUE THREAD

**Issue by KyrosDigital** [apercova/atom-path-intellisense#2]
When attempting to use with import from statements ... 

import { something } from '../../'

doesn't engage package. 

With a high volume of import statements in a project, this package would be more useful. 

Happy to collaborate on an update!

**Comment by apercova** [comment]
Hi @KyrosDigital. Lately I haven't had much spare time to maintain this package.
Collaborations are welcome. 
Please make a pull request with your fix and we can integrate it on a package update.
Regards.

**Comment by apercova** [comment]
Hi @KyrosDigital 

Release 1.2.0 is out!
Give it a try. It addresses this behaviour.

Once more contributions are welcome.
