### ISSUE TITLE
Not giving paths anymore

### ISSUE THREAD

**Issue by ajnauleau** [apercova/atom-path-intellisense#3]
All of a sudden I realized Atom wasn't giving me relative paths for files or directories. Not sure why, I started looking through my packages and realized that atom-path-intellisense wasn't working anymore.

Bug:

Not getting any path recommendations based on files or directories.

**Comment by apercova** [comment]
Hi @ajnauleau  sorry for reply this late.
I’m working on a new version and hope be able to release it soon.

**Comment by apercova** [comment]
Hi @ajnauleau 

Release 1.2.0 is out!
I've changed path suggestion mechanism to one  based providers.
Give it a try. 
Contributions are welcome.
