### ISSUE TITLE
configs disappear

### ISSUE THREAD

**Issue by aviatesk** [apercova/atom-path-intellisense#74]
When I restarted Atom after updating to v1.2.0, the config for this package seems to disappear.
(maybe [setting.js](https://github.com/apercova/atom-path-intellisense/blob/master/lib/config/settings.js) is not able to be loaded successfully)

And as a consequence, the default values for configs like `"manual-suggest": false` are also _unset_, and results in behaviours that are not described in README.

**Comment by aviatesk** [comment]
as a note:

> `atom --version`

```
$ atom --version

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

$ `apm --version`

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.1
git 2.24.0.windows.2
visual studio
```

OS: Windows 10
package version: 1.2.0

**Comment by apercova** [comment]
Thank's @aviatesk for submitting this issue. 
It seems to happen also when switch between dev and normal mode.
I'm working on a solution.

**Comment by aviatesk** [comment]
Nice. Hope you figure out the problem 😊

**Comment by apercova** [comment]
Hi @aviatesk .
You can update to [version 1.2.2](https://atom.io/packages/atom-path-intellisense). 
This issue with configuration for this package might have been solved.
If any further issue/doubt please leave a comment here.

**Comment by aviatesk** [comment]
@apercova Thanks for the quick response and fixing this ! v1.2.2 works very well for me :)

**Comment by apercova** [comment]
> @apercova Thanks for the quick response and fixing this ! v1.2.2 works very well for me :)

Nice!. Regards.
